name: flutter_tts_improved
description: A fork of the Flutter_TTS plugin, that uses the progress reporters of the Utterance APIs, on both Android and iOS.
version: 1.0.3
author: Loushou <life.42@gmail.com>
homepage: https://github.com/loushou/flutter_tts_improved

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.rdygo.flutter_tts_improved
    pluginClass: FlutterTtsImprovedPlugin
